apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: sonar-data
              mountPath: /opt/sonarqube/data
            - name: sonar-extensions
              mountPath: "/opt/sonarqube/extensions/"
          securityContext:
            runAsUser: 0  # Set the user ID to root
            runAsGroup: 0  # Set the group ID to root
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - SYS_ADMIN
      volumes:
        - name: sonar-data
          persistentVolumeClaim:
            claimName: sonar-data
        - name: sonar-extensions
          persistentVolumeClaim:
            claimName: sonar-extensions    
