apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:7.7-community
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: sonar-data
              mountPath: /opt/sonarqube/data
            - name: sonar-extensions
              mountPath: "/opt/sonarqube/extensions/"
          securityContext:
            fsGroup: 999
      volumes:
        - name: sonar-data
          persistentVolumeClaim:
            claimName: sonar-data
        - name: sonar-extensions
          persistentVolumeClaim:
            claimName: sonar-extensions    
