apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gitops
  name: gitops
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitops
    spec:
      containers:
      - image: timcicd/gitops:28
        ports:
            - containerPort: 9990
        name: gitops
        resources: {}
status: {}
